spring.application.name=SubCategory
server.port=10000
server.address=0.0.0.0
spring.datasource.url=mysql://root:eIPWUZAnvYnQFVdIQHASRmzSFdyLIJHz@autorack.proxy.rlwy.net:27894/railway
spring.datasource.username=root
spring.datasource.password=eIPWUZAnvYnQFVdIQHASRmzSFdyLIJHz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.csrf.enabled=true
